name: build-push consumer

on:
  workflow_dispatch:
    inputs:
        auto_deploy:
            description: 'auto deploy to devops-k8s'
            required: true
            type: boolean
            default: false
        blast:
            description: 'blast'
            required: true
            type: boolean
            default: false
        mmseqs2:
            description: 'mmseqs2'
            required: true
            type: boolean
            default: false
        evotune:
            description: 'evotune'
            required: true
            type: boolean
            default: false
        fittop:
            description: 'fittop'
            required: true
            type: boolean
            default: false
        mutation:
            description: 'mutation'
            required: true
            type: boolean
            default: false
jobs:
  build-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          lfs: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.IMAGE_REPO }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    
    - name: Get short commit SHA
      run: |
        export SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        echo "SHORT_SHA=${SHORT_SHA}" >> ${GITHUB_ENV}
        
    - name: Build and push blast service
      if: ${{ inputs.blast == true }}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./projects/blast/docker/consumer.Dockerfile
        push: true
        tags: ${{ secrets.IMAGE_REPO }}/${{ secrets.REGISTRY_USERNAME }}/ml-blast:consumer-${{ env.SHORT_SHA }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and push mmseqs2 service
      if: ${{ inputs.mmseqs2 == true }}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./projects/mmseqs2/docker/consumer.Dockerfile
        push: true
        tags: ${{ secrets.IMAGE_REPO }}/${{ secrets.REGISTRY_USERNAME }}/ml-mmseqs2:consumer-${{ env.SHORT_SHA }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and push evotune service
      if: ${{ inputs.evotune == true }}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./projects/evotune/docker/consumer.Dockerfile
        push: true
        tags: ${{ secrets.IMAGE_REPO }}/${{ secrets.REGISTRY_USERNAME }}/ml-evotune:consumer-${{ env.SHORT_SHA }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and push fittop service
      if: ${{ inputs.fittop == true }}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./projects/fittop/docker/consumer.Dockerfile
        push: true
        tags: ${{ secrets.IMAGE_REPO }}/${{ secrets.REGISTRY_USERNAME }}/ml-fittop:consumer-${{ env.SHORT_SHA }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push mutation service
      if: ${{ inputs.mutation == true }}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./projects/mutation/docker/consumer.Dockerfile
        push: true
        tags: ${{ secrets.IMAGE_REPO }}/${{ secrets.REGISTRY_USERNAME }}/ml-mutation:consumer-${{ env.SHORT_SHA }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
  
  deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest
    needs: build-push
    if: ${{ github.event.inputs.auto_deploy }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get image tag
        run: |
          export SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo $SHORT_SHA
          echo "IMAGE_TAG=consumer-${SHORT_SHA}" >> ${GITHUB_ENV}

      - name: Get image list
        run: |
          export BLAST_IMAGE=
          export MMSEQS2_IMAGE=
          export EVOTUNE_IMAGE=
          export FITTOP_IMAGE=
          export MUTATION_IMAGE=
          if [[ ${{ github.event.inputs.blast }} == true ]]; then export BLAST_IMAGE=${{ secrets.REGISTRY_USERNAME }}/ml-blast; fi
          if [[ ${{ github.event.inputs.mmseqs2 }} == true ]]; then export MMSEQS2_IMAGE=${{ secrets.REGISTRY_USERNAME }}/ml-mmseqs2; fi
          if [[ ${{ github.event.inputs.evotune }} == true ]]; then export EVOTUNE_IMAGE=${{ secrets.REGISTRY_USERNAME }}/ml-evotune; fi
          if [[ ${{ github.event.inputs.fittop }} == true ]]; then export FITTOP_IMAGE=${{ secrets.REGISTRY_USERNAME }}/ml-fittop; fi
          if [[ ${{ github.event.inputs.mutation }} == true ]]; then export MUTATION_IMAGE=${{ secrets.REGISTRY_USERNAME }}/ml-mutation; fi
          export IMAGE_LIST=$(python3 -c 'import os; print(",".join([e for e in [os.environ["BLAST_IMAGE"], os.environ["MMSEQS2_IMAGE"], os.environ["EVOTUNE_IMAGE"], os.environ["FITTOP_IMAGE"], os.environ["MUTATION_IMAGE"]] if e != ""]))')
          echo $IMAGE_LIST
          echo "IMAGE_LIST=${IMAGE_LIST}" >> ${GITHUB_ENV}

      - name: Auto Deploy to devops-k8s
        uses:  convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ProtEngPlus
          repo: devops-k8s
          github_token: ${{ secrets.ACTIONS_AUTH_TOKEN }}
          github_user: protenger
          workflow_file_name: update_tag_multiple.yaml
          client_payload: ${{ format('{{"path":"{0}","tag":"{1}","images":"{2}"}}', 'k8s/apps/ml-pipeline/overlays/dev/kustomization.yaml', env.IMAGE_TAG, env.IMAGE_LIST) }}