name: Test Build Microservices Images

on:
    push:
        branches:
        - '*'

jobs:
    blast-service:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
            
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Get short commit SHA
          run: |
            export SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
            echo "SHORT_SHA=${SHORT_SHA}" >> ${GITHUB_ENV}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./internal
            file: ./internal/blast-microservice/Dockerfile
            push: false
            tags: blast-service:${{ env.SHORT_SHA }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
    evotune-service:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
            
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Get short commit SHA
          run: |
            export SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
            echo "SHORT_SHA=${SHORT_SHA}" >> ${GITHUB_ENV}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./internal
            file: ./internal/evotune-microservice/Dockerfile
            push: false
            tags: blast-service:${{ env.SHORT_SHA }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
    fittop-service:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
            
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Get short commit SHA
          run: |
            export SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
            echo "SHORT_SHA=${SHORT_SHA}" >> ${GITHUB_ENV}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./internal
            file: ./internal/fittop-microservice/Dockerfile
            push: false
            tags: blast-service:${{ env.SHORT_SHA }}
            cache-from: type=gha
            cache-to: type=gha,mode=max